### ISSUE TITLE
The 11th attendee can't be removed from the Settings/Attendees list

### ISSUE THREAD

**Issue by na-ge-ma** [zeletrik/dsm-timer#26]
Detected on January 19th 2020 Android version. Huawei P9 pro and P10 lite is affected for sure.

Steps to reproduce:
1. Open the application
2. Tap on the "Settings" icon
3. Expand the "Attendees List" section
4. Tap on the "Configure list" button
5. Add more than 11 attendees to the list
6. Try to remove the 11th attendee from the list via swiping it to the left

Actual result:
The attendee can't be removed. All the other attendees can be removed easily.

Expected result:
The 11th attendee should be removable.

Thanks in advance.
Regards, from the Team. We miss you :)

**Comment by zeletrik** [comment]
Issue fixed, Google Play rollout started. 
Also, this project will soon move to a Flutter based one, just an FYI :) 

Cheers'
